CREATE DATABASE DOANBANTRANGSUCJAVA CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
USE DOANBANTRANGSUCJAVA;
CREATE TABLE AUTHORIZES (
  ID_AUTHORIZE INT AUTO_INCREMENT PRIMARY KEY,
  AUTHORIZE_NAME VARCHAR(20) NOT NULL
);
CREATE TABLE CUSTOMER (
  ID_CUSTOMER INT AUTO_INCREMENT PRIMARY KEY,
  FULLNAME VARCHAR(50) NOT NULL,
  PHONE_NUMBER VARCHAR(10) NOT NULL,
  BIRTHDAY date
);
CREATE TABLE STAFF (
  ID_STAFF INT AUTO_INCREMENT PRIMARY KEY,
  FULLNAME VARCHAR(50) NOT NULL,
  PHONE_NUMBER VARCHAR(10) NOT NULL,
  BIRTHDAY date DEFAULT 'NONE',
  SALARY FLOAT DEFAULT 5000000,
  DATE_START DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE ACCOUNTS (
  ID_ACCOUNT INT AUTO_INCREMENT PRIMARY KEY,
  ID_AUTHORIZE INT NOT NULL,
  ID_STAFF INT NOT NULL,
  USERNAME VARCHAR(50) UNIQUE NOT NULL,
  PASS_WORD VARCHAR(50) NOT NULL,
  CREATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE CATEGORY (
  ID_CATEGORY INT AUTO_INCREMENT PRIMARY KEY,
  CATEGORY_NAME VARCHAR(50) NOT NULL
);
CREATE TABLE MATERIAL (
  ID_MATERIAL INT AUTO_INCREMENT PRIMARY KEY,
  MATERIAL_NAME VARCHAR(20) NOT NULL
);
CREATE TABLE PRODUCTS (
  ID_PRODUCT INT AUTO_INCREMENT PRIMARY KEY,
  ID_CATEGORY INT NOT NULL,
  ID_MATERIAL INT NOT NULL,
  PRODUCT_NAME VARCHAR(200) NOT NULL,
  QUANTITY_SOLD INT NOT NULL,
  LINK_IMAGE VARCHAR (50) NOT NULL,
  CREATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE PARTICULAR_PRODUCTS (
  ID_PRODUCT INT NOT NULL,
  SIZE INT NOT NULL,
  PRICE FLOAT NOT NULL,
  QUANTITY_REMAIN INT NOT NULL
);
CREATE TABLE BILLS (
  ID_BILL INT AUTO_INCREMENT PRIMARY KEY,
  ID_STAFF INT NOT NULL,
  ID_CUSTOMER INT NOT NULL,
  TOTAL_BILL FLOAT NOT NULL,
  DATE_BILL DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE PARTICULAR_BILLS (
  ID_BILL INT NOT NULL,
  ID_PRODUCT INT NOT NULL,
  SIZE INT NOT NULL,
  PRICE FLOAT NOT NULL,
  QUANTITY INT NOT NULL
);
CREATE TABLE RECEIPTS (
  ID_RECEIPT INT AUTO_INCREMENT PRIMARY KEY,
  ID_STAFF INT NOT NULL,
  TOTAL_PRICE FLOAT NOT NULL,
  DATE_RECEIPT DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE PARTICULAR_RECEIPTS (
  ID_RECEIPT INT NOT NULL,
  ID_PRODUCT INT NOT NULL,
  SIZE INT NOT NULL,
  QUANTITY INT NOT NULL,
  PRICE FLOAT NOT NULL
);
ALTER TABLE ACCOUNTS
ADD FOREIGN KEY (ID_STAFF) REFERENCES STAFF (ID_STAFF) ON DELETE CASCADE;
ALTER TABLE PRODUCTS
ADD FOREIGN KEY (ID_CATEGORY) REFERENCES CATEGORY (ID_CATEGORY);
ALTER TABLE PRODUCTS
ADD FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL (ID_MATERIAL);
ALTER TABLE PARTICULAR_PRODUCTS
ADD FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS (ID_PRODUCT) ON DELETE CASCADE;
ALTER TABLE BILLS
ADD FOREIGN KEY (ID_STAFF) REFERENCES STAFF (ID_STAFF);
ALTER TABLE BILLS
ADD FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMER (ID_CUSTOMER);
ALTER TABLE PARTICULAR_BILLS
ADD FOREIGN KEY (ID_BILL) REFERENCES BILLS (ID_BILL) ON DELETE CASCADE;
ALTER TABLE PARTICULAR_BILLS
ADD FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS (ID_PRODUCT);
ALTER TABLE RECEIPTS
ADD FOREIGN KEY (ID_STAFF) REFERENCES STAFF (ID_STAFF);
ALTER TABLE PARTICULAR_RECEIPTS
ADD FOREIGN KEY (ID_RECEIPT) REFERENCES RECEIPTS (ID_RECEIPT) ON DELETE CASCADE;
ALTER TABLE PARTICULAR_RECEIPTS
ADD FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCTS (ID_PRODUCT);